<a href="https://colab.research.google.com/github/Amuw9/cgitraining/blob/main/Que21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['figure.dpi'] = 110
pd.set_option('display.max_colwidth', 40)
print("Environment ready ✅")

Environment ready ✅

In [2]:
backlog = pd.DataFrame([
    {
        "name": "selef-serving belling dashboard",
        "user_business_value": 8,
        "time_criticality": 3,
        "risk_reduction": 4,
        "job_size": 5,
    },
      {
        "name": "fix-rare-edge-case-crash",
        "user_business_value": 2,
        "time_criticality": 9,
        "risk_reduction": 6,
        "job_size": 1,
    },
      {
        "name": "new on boarding redesign flow",
        "user_business_value": 9,
        "time_criticality": 6,
        "risk_reduction": 4,
        "job_size": 8,
    },
      {
        "name": "API rate limit increase",
        "user_business_value": 5,
        "time_criticality": 3,
        "risk_reduction": 2,
        "job_size": 2,
    },






])
backlog

,name,user_business_value,time_criticality,risk_reduction,job_size
0,selef-serving belling dashboard,8,3,4,5
1,fix-rare-edge-case-crash,2,9,6,1
2,new on boarding redesign flow,9,6,4,8
3,API rate limit increase,5,3,2,2

In [6]:
# 3. Compute WSJF
backlog["cost_of_delay"] = (
    backlog["user_business_value"] + backlog["time_criticality"] + backlog["risk_reduction"]
)
backlog["wsjf"] = (backlog["cost_of_delay"] / backlog["job_size"]).round(2)



ranked_wsjf = backlog.sort_values("wsjf", ascending=False).reset_index(drop=True)
ranked_wsjf.index += 1
ranked_wsjf[[ "wsjf"]]

    wsjf
1  17.00
2   5.00
3   3.00
4   2.38